FROM python:3.11

WORKDIR /app

LABEL maintainer="mikolajmizera@gmail.com"
LABEL version="0.1"
LABEL description="Envrinoment for running FinanceGPT project (@github)."

RUN apt-get update -y && \
    apt-get install -y wget bzip2

RUN wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh && \
    bash Anaconda3-2023.07-1-Linux-x86_64.sh -b && \
    rm Anaconda3-2023.07-1-Linux-x86_64.sh

# Set path to conda
ENV PATH /root/anaconda3/bin:$PATH

# Update Anaconda packages
RUN conda update conda

# Creating python environment
RUN conda create --name financegpt python=3.11 pre-commit

CMD sleep infinity