[build-system]
requires = ["setuptools"]

[project]
name = "FinanceGPT"
readme = "README.md"
requires-python = ">=3.11"

dynamic = ["version"]

dependencies = [
    "dvc==3.14.0",
    "dvc-s3==2.23.0"
]

[project.optional-dependencies]
test = [
    "black==23.7.0",
    "pytest==7.4.0",
    "flake8==6.1.0",
    "mypy==1.4.1"
]


[tool.setuptools.dynamic]
version = {attr = "financegpt.__version__"}