name: Liniting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        dvc pull
        
    - name: Check code formatting with Black
      run: |
        black --check .

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Test with pytest
      run: |
        pytest
